#!/usr/bin/env python3
"""Generate a class's member declarations from a list of known fields.

Big classes are only partly understood: a few dozen members at known offsets
in thousands of bytes. Writing the padding by hand is error-prone, so the
known members live in a `.fields` file next to the header, one per line:

    OFFSET SIZE TYPE NAME          # optional comment
    0x4C   4    void* unk4C
    0x533C 0x460 CASSelector unk533C[5]   # five selectors

and this script writes `NAME.inc` with the members and `char` padding in
between, to be #included inside the class body. FIRST and END give the offset
of the first byte the class itself owns and its total size.

Usage: tools/gen_fields.py path/Class.fields
"""
import sys
from pathlib import Path

src = Path(sys.argv[1])
first = end = None
fields = []
for raw in src.read_text().splitlines():
    line, _, comment = raw.partition("#")
    parts = line.split()
    if not parts: continue
    if parts[0] == "FIRST": first = int(parts[1], 0); continue
    if parts[0] == "END": end = int(parts[1], 0); continue
    fields.append((int(parts[0], 0), int(parts[1], 0), " ".join(parts[2:-1]), parts[-1], comment.strip()))
fields.sort()
out = [f"// Generated by tools/gen_fields.py from {src.name}. Do not edit."]
pos = first
for off, size, typ, name, comment in fields:
    if off < pos: sys.exit(f"{name} at {off:#x} overlaps the previous member (ends at {pos:#x})")
    if off > pos: out.append(f"    char pad{pos:X}[{off - pos:#x}];")
    out.append(f"    {typ} {name};" + (f" // {off:#x} {comment}" if comment else f" // {off:#x}"))
    pos = off + size
if end is not None:
    if end < pos: sys.exit(f"END {end:#x} is before the last member's end {pos:#x}")
    if end > pos: out.append(f"    char pad{pos:X}[{end - pos:#x}];")
src.with_suffix(".inc").write_text("\n".join(out) + "\n")
print(f"{len(fields)} members -> {src.with_suffix('.inc')}")
